### ISSUE TITLE
Adding color to listUnorderedItemIcon overwrites all defaults

### ISSUE THREAD

**Issue by petrogad** [mientjan/react-native-markdown-renderer#40]
Likely by design, however in my case, I just wanted to update the color property of the particular dot. I ended up pulling in the styles used to position it too.

Thoughts on allowing an extension of the style vs overwriting it?

**Comment by mientjan** [comment]
hey @petrogad, yea this is by design. So the list item your trying to style is done in the renderRule list_item. 

This is in https://github.com/mientjan/react-native-markdown-renderer/blob/master/src/lib/renderRules.js#L169
```js
  // li
  list_item: (node, children, parent, styles) => {
    if (hasParents(parent, 'bullet_list')) {
      return (
        <View key={node.key} style={styles.listUnorderedItem}>
          <Text style={styles.listUnorderedItemIcon}>{'\u00B7'}</Text>
          <View style={[styles.listItem]}>{children}</View>
        </View>
      );
    }

    if (hasParents(parent, 'ordered_list')) {
      return (
        <View key={node.key} style={styles.listOrderedItem}>
          <Text style={styles.listOrderedItemIcon}>{node.index + 1}</Text>
          <View style={[styles.listItem]}>{children}</View>
        </View>
      );
    }

    return (
      <View key={node.key} style={[styles.listItem]}>
        {children}
      </View>
    );
  },
```

What you could do is overwrite this particular rule with your own rule. This can be done see docs here. https://github.com/mientjan/react-native-markdown-renderer/wiki/Examples#simple-implementation-with-custom-rules

**Comment by petrogad** [comment]
Yep, I did exactly that.  I figured it was by design as someone would want to insert their own icon and potentially all their own styles.

I extended the defined styles from listUnorderedItemIcon and just re0implemented on my end.

Thank you for the response!
